[http.middlewares]
  [http.middlewares.chain-no-auth]
    [http.middlewares.chain-no-auth.chain]
      middlewares = [ "middleware-rate-limit", "middleware-secure-headers"]

  [http.middlewares.chain-basic-auth]
    [http.middlewares.chain-basic-auth.chain]
      middlewares = [ "middleware-rate-limit", "middleware-secure-headers", "middleware-basic-auth"]

  [http.middlewares.chain-authelia]
    [http.middlewares.chain-authelia.chain]
      middlewares = [ "middleware-rate-limit", "middleware-secure-headers", "middleware-authelia"]
      
  [http.middlewares.chain-nextcloud]
    [http.middlewares.chain-nextcloud.chain]
      middlewares = [ "middleware-rate-limit", "nextcloud-middleware-secure-headers", "nextcloud-middleware-redirect"]